### PR TITLE
Added queue extension

### PR DESCRIPTION
**Pull request by ruthmore**
I have added my 'queue' extension for NetLogo 6.1.

### CODE REVIEW

**Review by LaCuneta — CHANGES_REQUESTED** [review]
Hey Ruth,

Thank you very much for the contribution!  Just a couple changes needed:

1. In your zip file there is a subfolder, queue-extension-1.1.  The extension manager expects the jar files of an extension to be in the "root" of the zip folder so when extracted they will be ready to go.
2. In your edits to the `libraries.conf` file, I see some smart quotes got added in, as in `“Queue”` (but also in the other added lines).  We'll need these switched to straight-quotes, like `"Queue"`.    

I'll add these notes to our docs as well.

**Comment by ruthmore** [comment]
Hi Jeremy,

I've made the requested changes so my fork of the NetLogo Libraries is now correct (ruthmore/Netlogo-Libraries:6.1). In the process I also renamed the zip file from "queue-extension.zip" to just "queue.zip". Do I need to do anything else?

**Comment by LaCuneta** [comment]
Hey Ruth,

Thank you for fixing up the quotes!

For the zip file, I don't see one attached to this pull request anymore, just the old one removed.  Also, the name of the zip file was fine (`queue-extension-1.1.zip`), it was the contents inside of it that were different than we require.

Here is what was there before:

```
queue-extension-1.1.zip
  └──queue-extension-1.1/
       └──queue.jar
```

And here is what the Extension Manager expects, with no subfolder:

```
queue-extension-1.1.zip
  └──queue.jar
```

That might've been what you meant you did to change it up, but I just wanted to be sure.

**Comment by ruthmore** [comment]
Sorry for the confusion. The zip file somehow got left out of the git commit. I've remedied that now and it's definitely there. 

What I meant above is that when taking the subfolder out of the zip file I also renamed it to queue-1.1.zip (instead of queue-extension-1.1.zip) to be in keeping with naming conventions. 

This name change is also reflected in my changes to libraries.config so everything should be correct now (fingers crossed!).

**Comment by LaCuneta** [comment]
> What I meant above is that when taking the subfolder out of the zip file I also renamed it to queue-1.1.zip (instead of queue-extension-1.1.zip) to be in keeping with naming conventions.

Gotcha, yeah, just wanted to be sure.  Everything now looks good to me.  Thank you again!

**Pull request merged**
