### PR TITLE
add rngs-2.0

### PR DESCRIPTION
**Pull request by AFMac**
Added update to expanded random number generation extension.

### CODE REVIEW

**Review by LaCuneta — CHANGES_REQUESTED** [review]
Thank you for you submission!

- For the `downloadURL` field, you can use a path to our `NetLogo-Libraries` repository, which would be `https://raw.githubusercontent.com/NetLogo/NetLogo-Libraries/6.1/extensions/rngs-2.0.zip` after the pull request is merged.
- The `rngs.jar` should include a `MANIFEST.MF` file with the property `NetLogo-Extension-API-Version: 6.1`.  At the moment, it doesn't seem to have `NetLogo-Extension-API-Version` included at all, so NetLogo shows a warning when the extension is loaded.  The steps to get this added to the jar will depend on your build tools and processes.
- I don't see much documentation at the homepage link, https://github.com/AFMac/rngs.  Is there a page somewhere documenting the included extension primitives and how to use them in a model?  We don't require this documentation exactly, it'd just be nice to link to if it exists.

Let me know if you have any questions.

-Jeremy

**Comment by AFMac** [comment]
Jeremy-

I'll update the download link, no sweat.  The rngs.jar file did have a manifest file included, although I used 6.0 instead of 6.1, following the example on the extension authoring page.   I noticed the warning message pop-up as well when I ran a quick test.  I updated the manifest to point 6.1 and remade the .jar file and am still getting the same pop-up.  Is there something I'm missing?

**Comment by LaCuneta** [comment]
Here is what I see in the `MANIFEST.MF` file inside the jar:

```
Manifest-Version: 1.0
Extension-Name: rngs
Class-Manager: RNGExtension
Created-By: 11.0.5 (AdoptOpenJDK)

```

I'm not exactly sure why just the NetLogo API version setting would be getting dropped.  [Our docs say](https://github.com/NetLogo/NetLogo/wiki/Extensions-API#3-write-a-manifest) there needs to be a newline at the end of file.  Could that be the problem?

**Comment by AFMac** [comment]
Doh!  Newline was the issue.  Will rewicker everything and re-commit.  I'll also expand the documentation a little:  I included an example model with syntax usage as part of the distro, and will ensure at least that level of detail is reflected.

Thanks again!

**Comment by AFMac** [comment]
@LaCuneta Changes made as per above.  Download link corrected along with the manifest file.  Thanks for the help!

**Review by LaCuneta — APPROVED** [review]

**Pull request merged**
