### PR TITLE
Factbase extension

### PR DESCRIPTION
**Pull request by ruthmore**
I have added my factbase extension for NetLogo 6.1.

### CODE REVIEW

**Comment by LaCuneta** [comment]
Hey Ruth, thank you for the submission.  

I extracted the extension from the zip file and everything looked good and worked fine.  The changes to the `libraries.conf` file also look good. 

I see some extra commits that aren't needed, about a `.gitignore` file and about the Queue extension that was previously merged.  I think we just need [this commit](https://github.com/NetLogo/NetLogo-Libraries/pull/25/commits/32650f03b414c04534c61ab30a5b321d961d4258) added on top of the latest `6.1` without the extras and this will be ready to merge.

**Comment by ruthmore** [comment]
Hi Jeremy,

I'd love to do that but have to confess that I don't know how. I'm obviously no expert in git, sorry. I suppose the problem with the queue stuff still in there is due to me trying to update my fork of the NetLogo-Libraries instead of doing a new one for the factbase extension.

So how do I best proceed?

**Comment by LaCuneta** [comment]
Ruth,

No worries git can be a very finicky beast and takes a while to get used to.  Below are the steps I would follow to get this pull request up-to-date with the latest changes and to get cleaned up to just the commit we want to see.

```
# 0. Change directory to your local copy of the NetLogo-Libraries repository
cd path/to/NetLogo-Libraries

# 1. Check which remotes we have already know about
git remote -v

# 2. If you see a remote already setup for https://github.com/NetLogo/NetLogo-Libraries.git (different than your fork in https://github.com/ruthmore/NetLogo-Libaries.git which is probably listed as `origin`),
# then you can skip this step and use that instead of `upstream` in the steps below.
# If you do not see one, we have to add it
git remote add upstream https://github.com/NetLogo/NetLogo-Libraries.git

# 3. Get our `upstream` info up-to-date, this won't change anything yet
git fetch upstream

# 4. Look at status, should still be on branch `6.1` with no uncommitted files
git status

# 5. Make a new branch to backup the commits we already have
# Note we don't `git checkout factbase` as the active branch, we just want to make it as a backup.
git branch factbase

# 6. Reset the local `6.1` branch to be like the current `6.1` in NetLogo/NetLogo-Libraries
git reset --hard upstream/6.1

# 7. Cherry-pick the one commit we want by commit hash, "added factbase extension"
# You could also manually re-apply your changes (zip file and `libraries.conf`) and add a brand new commit instead.
git cherry-pick 32650f0

# 8. Check that everything worked and looks okay, 1 new commit on top
git status
git log -5

# 9. A force push will overwrite what you had before and should update the pull request
git push --force-with-lease origin 6.1
```

In general my recommendation would be to work on a separate branch for each extension you submit or update so you can keep your `6.1` branch clear and up-to-date with the changes we add here.  That should make the process a little smoother.  I'll try to write up some documentation on that for you and others to use in the future.

I hope that helps, let me know if you have any trouble with it.

**Comment by ruthmore** [comment]
Jeremy,

thanks for your help. I've done everything up to step 8 now but would like to check with you before I do step 9. The result of `git status` looks like this:

`Ruths-MacBook-Air-2:NetLogo-Libraries ruth$ git status`
`On branch 6.1`
`Your branch and 'origin/6.1' have diverged,`
`and have 9 and 6 different commits each, respectively.`
 ` (use "git pull" to merge the remote branch into yours)`
`Untracked files:`
 ` (use "git add <file>..." to include in what will be committed)`

`	.DS_Store`
`	extensions/.DS_Store`

`nothing added to commit but untracked files present (use "git add" to track)`

and the beginning of `git log -5` is this:

`Ruths-MacBook-Air-2:NetLogo-Libraries ruth$ git log -5`
`commit e475467257837d2a7dbb830070f951477266385b`
`Author: ruthmore <meyer.ruth@gmail.com>`
`Date:   Sun Nov 17 14:55:29 2019 +0000`

`    added factbase extension`

`commit f0568e14659dba87f96966824e1ffcbfd688e0cf`
`Author: LaCuneta <jeremy.baker@northwestern.edu>`
`Date:   Tue Nov 19 15:21:14 2019 -0600`

`    Docs: Add a note about multi-platform extensions`

`commit af8bad76e6e96bf384c58a140339a5d8deb869a3`
`Author: Bryan Head <bryan.head@gmail.com>`
`Date:   Fri Nov 8 08:56:17 2019 -0800`

`    Update LS to 2.3.0`

`commit d53176608a767e91ba61a050e9cc46137c5a3f5f`
`Author: aab77 <aab77@users.noreply.github.com>`
`Date:   Wed Nov 13 11:18:56 2019 -0600`

`    view2.5d-1.1.4`

Does that look right to you? I'm a bit worried about the "9 and 6 different commits, respectively".

**Comment by LaCuneta** [comment]
That `git log` looks right to me, that's the latest from our `6.1` branch with your fact base commit on top.  You should be ready for step 9, to force push.  

The status is telling you about the diverged commit differences (9 and 6) with your GitHub `6.1` branch, since that's got the out-of-date commits for queue extension and the `.gitignore` changes (the 9), and our `6.1` branch you pulled in has some commits you handn't seen before (the 6).  Also, you have the backup branch from step 5, as well, so you have a fallback if it isn't right.

**Comment by ruthmore** [comment]
OK, I've done step 9! I think it went as intended since only "2 local objects" are mentioned:

`Ruths-MacBook-Air-2:NetLogo-Libraries ruth$ git push --force-with-lease origin 6.1`
`Counting objects: 5, done.`
`Delta compression using up to 4 threads.`
`Compressing objects: 100% (5/5), done.`
`Writing objects: 100% (5/5), 220.92 KiB | 0 bytes/s, done.`
`Total 5 (delta 2), reused 0 (delta 0)`
`remote: Resolving deltas: 100% (2/2), completed with 2 local objects.`
`To https://github.com/ruthmore/NetLogo-Libraries.git`
 `+ 14aa99c...e475467 6.1 -> 6.1 (forced update)`

**Comment by LaCuneta** [comment]
Awesome, yes, everything looks good when I check [the files list for this PR](https://github.com/NetLogo/NetLogo-Libraries/pull/25/files).  Thank you so much for working on the changes and for submitting the extension.

**Comment by ruthmore** [comment]
Thank you very much for your help and patience! 

One last question (not quite related): Where does the NetLogo Extension Manager actually install the extensions? I deleted my local factbase installation for NetLogo 6.1.1 since it was flagged as a conflicting library and chose to install it again via the Extension Manager. It works but I cannot see it in the file system at all. It certainly doesn't show up as a folder "factbase" in "extensions". 

I'm asking because I am wondering how people will be able to access the bundled example models if they can't see the folder they are in? I've tried this now on both Mac and Windows and I can't see it in the NetLogo extensions folder on either platform. 

If you're not the right person to ask this, could you point me in the right direction please?

**Comment by LaCuneta** [comment]
Hey Ruth,

The extension managers installs to a user-dependent directory, as laid out [in item 3 of these docs](https://ccl.northwestern.edu/netlogo/docs/extensions.html#where-extensions-are-located).  

You bring up a great point with the example models.  They are installed and users could find them if they knew where to look, but the locations are a little obscure.  I'll make sure to open a NetLogo issue for this so we can come up with a better solution in the future.

In the meantime, the next best thing I can think to offer besides pointing people to the install directory is to link to the examples from the documentation, so users can download them to a location of their choice.

**Pull request merged**
