### PR TITLE
Update the NumAnal extension to Version 3.4.0

### PR DESCRIPTION
**Pull request by cstaelin**
Updates numanal to version 3.4.0, which contains a new linear programming routine.

### CODE REVIEW

**Review by LaCuneta — CHANGES_REQUESTED** [review]
Thank you for the update!  This pull request looks like it might not have been based on the latest changes to the NetLogo-Libraries repository.  Maybe a fetch/pull/rebase is needed?

- It's re-adding the extension to the `libraries.conf` when it already exists there in the `6.1` branch.  It should just be updating the version and file name (and other information as needed).
- It's re-adding the version 3.3.0 zip file, which we shouldn't need, as it's already there.

Once those issues are cleared up, I can get this merged.  Thanks, again.

**Comment by cstaelin** [comment]
Thanks.  I'll do a fresh fork from NetLogo-Libraries, make the changes and
submit a new pull.

Charles

-------------------------------
Charles P. Staelin
Professor of Economics
Smith College
Northampton, MA 01063

**Comment by cstaelin** [comment]
I noticed today that there was a commit to NetLogo-Libraries after I forked
it.  But the real problem, I think, was that the long description I edited
accidentally lost its closing quotation marks, and of course the old
version of the zip file was there with the new.  I do see that some
extensions do have multiple versions in the extensions directory.  When is
that appropriate, and when not?

Thanks,
Charles

-------------------------------
Charles P. Staelin
Professor of Economics
Smith College
Northampton, MA 01063

**Comment by LaCuneta** [comment]
> ... the old version of the zip file was there with the new. I do see that some extensions do have multiple versions in the extensions directory. When is that appropriate, and when not? Thanks, 

Leaving old versions of the zip in the repository is not a problem at all, you can just add your new one and update the `libraries.conf` file to point to it.  The issue I saw was this pull request re-added the old version zip file for some reason, which already existed in the repository so wasn't necessary.

I'll take a look at the new PR.

**Comment by cstaelin** [comment]
That is curious.  Perhaps I deleted the old version and then changed my
mind?  In any event, you should have a new pull request that hopefully is
okay, although looking just now I don't see it on my end.  Was it closed
with the old one (#21)?

-------------------------------
Charles P. Staelin
Professor of Economics
Smith College
Northampton, MA 01063

**Comment by LaCuneta** [comment]
The new pull request is here: https://github.com/NetLogo/NetLogo-Libraries/pull/23

**Pull request closed without merging**
