### PR TITLE
Adding qlearningextension

### PR DESCRIPTION
**Pull request by KevinKons**

### CODE REVIEW

**Comment by LaCuneta** [comment]
Thank you for the submission!  I'll try to review it later today or tomorrow.

**Comment by KevinKons** [comment]
> Thank you for the submission! I'll try to review it later today or tomorrow.

Thank you

**Review by LaCuneta — APPROVED** [review]
Looks good to me, I might recommend changing the extension code name to something like `qlearning` or even `ql` in a future release.  The extra `extension` in `qlearningextension` doesn't add a lot of info when you're working in NetLogo code, and adds a whole lot more typing.

**Comment by KevinKons** [comment]
Ok, I will do that in future release. Thanks for the advice!

**Pull request merged**
